# NOTE: Integration tests are part of a separate workflow so we can re-run just
# this workflow on failure
name: Integration Tests

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: read  # for actions/checkout to fetch code

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  # Needed if we want colors in pytest output without tty and script -e -c wrapper
  PY_COLORS: "1"
  FORCE_COLOR: "1"

jobs:
  integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        python_version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v6
      - name: Use Python ${{ matrix.python_version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867

      - name: Install OS / deb dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq gcc libvirt-dev pkg-config

      - name: Cache uv
        uses: actions/cache@v5
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install Python Dependencies
        run: |
          uv sync --group ci --no-dev
          echo "${GITHUB_WORKSPACE}/.venv/bin" >> "$GITHUB_PATH"

      - name: Run tox target
        run: |
          tox -e integration-storage
        env:
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
